config/routes.rb
Rails.application.routes.draw do

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  # resources :home, only: [:show]

  root to: "site#index"

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :categories, only: [:index, :show]

  resources :users, only: [:new, :create]

  resources :items, only: [:index, :show]

  resources :basket_carts, only: [:index, :create]

  resources :baskets, only: [:new, :show, :index]

  resources :carts, only: [:index, :create]

  namespace :api do
    namespace :v1 do
      resources :items, only: [:index, :create, :destroy, :update]
    end
  end


end

app/models/Item.rb
class Item < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :category
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
  belongs_to :user
  has_many :basket_items
  has_many :items, through: :basket_items

  def add(item_hash)
    item_hash.each do |item, quantity|
      items << item
      basket_item = BasketItem.find_by(basket: self, item_id: item.id)
      basket_item.update(quantity: quantity)
    end
  end


end

app/models/basket_cart.rb
class BasketCart
  attr_reader :contents
  def initialize(initial_contents)
    @contents = initial_contents || {}
  end

  def add_item(id)
    contents[id.to_s] = (contents[id.to_s] || 0) + 1
  end

  def count_of(id)
    contents[id.to_s].to_i
  end

  def item_and_quantity
    items = {}
    contents.each do |item_id, quantity|
      items[Item.find(item_id)] = quantity
    end
    items
  end

  def destroy
    @contents.clear
  end

end

app/models/basket_item.rb
class BasketItem < ApplicationRecord
  belongs_to :basket
  belongs_to :item
end

app/models/cart.rb
class Cart
  attr_reader :contents
  def initialize(initial_contents)
    @contents = initial_contents || {}
  end

  def add_basket(id)
    contents[id.to_s] = (contents[id.to_s] || 0) + 1
  end

  def count_of(id)
    contents[id.to_s].to_i
  end

  def basket_and_quantity
    baskets = {}
    contents.each do |basket_id, quantity|
      baskets[Basket.find(basket_id)] = quantity
    end
    baskets
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
end

app/models/nutrition.rb
class Nutrition
  attr_reader :serving_quantity,
              :serving_weight,
              :calories,
              :total_fat,
              :sat_fat,
              :cholesterol,
              :sodium,
              :carbohydrates,
              :fiber,
              :sugar,
              :protein,
              :potassium

  def initialize(nutrition_hash)
    @serving_quantity = nutrition_hash[:serving_qty]
    @serving_weight = nutrition_hash[:serving_weight_grams]
    @calories = nutrition_hash[:nf_calories]
    @total_fat = nutrition_hash[:nf_total_fat]
    @sat_fat = nutrition_hash[:nf_saturated_fat]
    @cholesterol = nutrition_hash[:nf_cholesterol]
    @sodium = nutrition_hash[:nf_sodium]
    @carbohydrates = nutrition_hash[:nf_total_carbohydrate]
    @fiber = nutrition_hash[:nf_dietary_fiber]
    @sugar = nutrition_hash[:nf_sugars]
    @protein = nutrition_hash[:nf_protein]
    @potassium = nutrition_hash[:nf_potassium]
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :baskets
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.email = auth.info.email
      user.password = 'password'
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

end

app/models/vegetable.rb
class Vegetable < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  respond_to :json
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  helper_method :current_user
  before_action :set_cart, :set_basket

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def set_cart
    @cart ||= Cart.new(session[:cart])
  end

  def set_basket
    @basket_cart ||= BasketCart.new(session[:basket_cart])
  end

  def require_current_user
    render file: "/public/404" unless current_user
  end

end

app/controllers/basket_carts_controller.rb
class BasketCartsController < ApplicationController
      include ActionView::Helpers::TextHelper
  def index
    @items = @basket_cart.item_and_quantity
  end

  def create
    item = Item.find(params[:item_id])
    @basket_cart.add_item(item.id)
    session[:basket_cart] = @basket_cart.contents
    flash[:notice] = "You now have #{pluralize(@basket_cart.count_of(item.id), item.name)}."
    redirect_back(fallback_location: root_path)
  end



end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  before_action :require_current_user

  def index
    @baskets = current_user.baskets.all
  end

  def new
    basket = Basket.create(user_id: current_user.id)
    item_hash = @basket_cart.item_and_quantity
    basket.add(item_hash)
    @basket_cart.destroy
    flash[:success] = "Basket was successfully created"
    redirect_to basket_path(basket)
    # redirect_to carts_path(basket_id: basket.id), method: :post
  end

  def show
    @basket = Basket.find(params[:id])
  end


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    include ActionView::Helpers::TextHelper
  def index
    @baskets = @cart.basket_and_quantity
  end

  def create
    basket = Basket.find(params[:basket_id])
    @cart.add_basket(basket.id)
    session[:cart] = @cart.contents
    flash[:notice] = "You now have #{pluralize(@cart.count_of(basket.id), "basket")} in your cart."
    redirect_to carts_path
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @nutrition = NutritionInfoService.new.nutrition_info(@category.title)
    @items = @category.items
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end

end
# 

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    # @nutrion = NutritionInfoService.new.nutrition(@item.name)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if params[:provider].present?
      @user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      @user = User.find_by(email: params[:session][:email])
      verify_user
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

    def verify_user
      if @user && @user.authenticate(params[:session][:password])
        login_successful
      else
        flash[:failure] = "That login was unsuccessful"
        redirect_to login_path
      end
    end

    def login_successful
      session[:user_id] = @user.id
      redirect_to root_path
    end


end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/basket_carts/index.html.erb
<div class="container">
    <% if current_user  %>
        <h3> <%= current_user.first_name %>'s  Basket</h3>
    <% else %>
        <h3> Your Basket </h3>
    <% end %>
    <h6><%= link_to "Continue Shopping", items_path %></h6>
	<center>
	<!-- <div class="col-10"> -->
	<table class="table table-hover">
	  <thead>
	    <tr>
	      <th>Name</th>
        <th></th>
        <th>Price</th>
        <th>Unit Measurement</th>
        <th>Quantity</th>
	    </tr>
      <tbody>

    <% @items.each do |item, quantity| %>
      <div class="item-#{item.id}">
        <tr>
        <th scope="row"><strong><%= link_to item.name, item_path(item) %></strong></th>
        <td><%= image_tag item.image_path, size: "3" %></td>
        <td>$<%= item.price %></td>
        <td>$<%= item.unit_measurement %></td>
        <td><%= quantity %></td>
      </tr>
      </div>
      <% end %>
    </tbody>
    </table>
    <div class="checkout">
      <% if current_user %>
      <%= link_to "Create Basket", new_basket_path(items: @items) %>

      <% else %>
        <%= link_to "Login", login_path %> <br />
        <%= link_to "Create New Account", new_user_path %>
      <% end %>
    </div>
  <!-- </div> -->
</center>
</div>

app/views/baskets/index.html.erb
<div class="container">
  <div class="row">>
    <%= @baskets.each do |basket| %>
    <div class="center-block">
      <div class="card border-white" style="width: 15rem;">
        <%= image_tag "/images/basket.jpg", size: "250" %>
        <div class="card-body">
          <center><p><strong>Items in Basket</strong></p>
          <% basket.items.each do |item| %>
            <center><p><%= link_to item.name, item_path(item) %></p>
          <% end %>
          <center><p><%= link_to "Add to Cart", carts_path(basket_id: basket.id), method: :post %></p>
          </div>
        </div>
      </div>
      <% end %>

    </div>
  </div>

app/views/baskets/show.html.erb
<div class="container">
  <div class="row">>

    <div class="center-block">
      <div class="card border-white" style="width: 15rem;">
        <%= image_tag "/images/basket.jpg", size: "250" %>
        <div class="card-body">
          <center><p><strong>Items in Basket</strong></p>
          <% @basket.items.each do |item| %>
            <center><p><%= link_to item.name, item_path(item) %></p>
          <% end %>
          <center><p><%= link_to "Add to Cart", carts_path(basket_id: @basket.id), method: :post %></p>

          </div>
        </div>
      </div>

    </div>
  </div>

app/views/carts/index.html.erb
<div class="container">
    <% if current_user  %>
        <h3> <%= current_user.first_name %>'s  Cart</h3>
    <% else %>
        <h3> Your Cart </h3>
    <% end %>
    <h6><%= link_to "Continue Shopping", items_path %></h6>
	<center>
	<!-- <div class="col-10"> -->
	<table class="table table-hover">
	  <thead>
	    <tr>
	      <th>Basket</th>

        <th>Quantity</th>
	    </tr>
      <tbody>

    <% @baskets.each do |basket, quantity| %>
      <div class="item-#{item.id}">
        <tr>
        <th scope="row"><strong><%= link_to "Basket #{basket.id}", basket_path(basket) %></strong></th>
        <td><%= quantity %></td>
      </tr>
      </div>
      <% end %>
    </tbody>
    </table>
    <div class="checkout">
      <% if current_user %>
        checkout

      <% else %>
        <%= link_to "Login", login_path %> <br />
        <%= link_to "Create New Account", new_user_path %>
      <% end %>
    </div>

</center>
</div>

app/views/categories/index.html.erb
<div class="container">
  <div class="row">
    <% @categories.each do |category| %>


    <div class="center-block">
      <div class="card border-white" style="width: 15rem;">
        <%= image_tag "/images#{category.items.first.image_path}", size: "250" %>
        <div class="card-body">
          <center><p><strong><%= link_to "#{category.title}", category_path(category) %></strong></p>

          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>

app/views/categories/show.html.erb
<h1><%= @category.title %></h1>
<h2>Nutrition Info</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Nutrition Fact</th>
      <th>Amount</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Serving Quantity</td>
      <td><%= @nutrition.serving_quantity %></td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Serving Weight</td>
      <td><%= @nutrition.serving_weight %></td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Total Fat</td>
      <td><%= @nutrition.total_fat %></td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Saturated Fat</td>
      <td><%= @nutrition.sat_fat %></td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Cholesterol</td>
      <td><%= @nutrition.cholesterol %></td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Sodium</td>
      <td><%= @nutrition.sodium %></td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Carbohydrates</td>
      <td><%= @nutrition.carbohydrates %></td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Fiber</td>
      <td><%= @nutrition.fiber %></td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Sugar</td>
      <td><%= @nutrition.sugar %></td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Protein</td>
      <td><%= @nutrition.protein %></td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Potassium</td>
      <td><%= @nutrition.potassium %></td>
    </tr>

  </tbody>
</table>



<div class="container">
  <div class="row">
    <% @items.each do |item| %>
    <div class="center-block">
      <div class="card border-white" style="width: 15rem;">
        <%= image_tag "/images#{item.image_path}", size: "250" %>
        <div class="card-body">
          <center><p><strong><%= link_to item.name, item_path(item) %></strong></p>
            <!-- <p>Description: <%= item.description %></p> -->
            <p>Price: $<%= item.price %></p>
            <p>Per: <%= item.unit_measurement %></p>
            <p><%= item.description %></p>
            <%= link_to "Add to Basket", basket_carts_path(item_id: item.id), method: :post, class: "badge badge-primary" %>

          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
<%= f.label :first_name  %>
<%= f.text_field :first_name %>

<%= f.label :last_name  %>
<%= f.text_field :last_name %>

<%= f.label :email  %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.text_field :password %>

<%= f.submit "Create Account" %>

<% end %>

app/views/users/new.html.erb
<%= render partial: "form" %>